locales:
  /:
    lang: en-US
    langName: EN
    title: Cheng Shang |Homepage
    description: I conduct research in Quantum Theory.
    ui:
      themeToggle: Toggle Theme
      contact: Contact

    hero:
      name: Cheng Shang
      welcome: üëã Hi there, I am
      titles:
        - ‚Ñè Theoretical Physics Researcher
        - ‚ôú INTJ (MBTI) ‚û∂ Sagittarius
      avatar: /avatar.avif
      bgImage: /bg.avif
      medias:
        - icon: fa6-brands:orcid
          name: ORCID
          link: https://orcid.org/0000-0001-8393-2329

        - icon: fa6-brands:google-scholar
          name: Google Scholar
          link: https://scholar.google.com/citations?user=-k8PWr8AAAAJ

        - icon: fa6-brands:linkedin-in
          name: iNSPIRE
          link: https://inspirehep.net/authors/2662928

        - icon: fa6-solid:fire
          name: "Make time for civilization. Live proud. Never give up!"
          link: https://cheng-shang.me/

          
    navbar:
      links:
        - label: Profile
          anchor: "#profile"
        - label: Experience
          anchor: "#experience"
        - label: Achievements
          anchor: "#achievements"
        - label: Interests
          anchor: "#interests"


    sections:
      - type: profile
        id: profile
        title: Profile
        icon: user-tie
        data:
          fields:
            - title: Affiliation
              icon: building-columns
              value: Analytical Quantum Complexity RIKEN Hakubi Research Team |RIKEN Center for Quantum Computing
            - title: Position
              icon: user-graduate
              value: Postdoctoral Researcher

          contacts:
            - label: RIKEN Email
              value: cheng.shang@riken.jp
              icon: fa6-solid:envelope

            - label: Gmail
              value: shangc1204@gmail.com
              icon: fa6-brands:google

            - label: X |Social Media
              value: "@Shangc1204"
              icon: fa6-brands:x-twitter

              

      - type: experience
        id: experience
        title: Experience
        icon: briefcase
        data:
          - type: work
            place: Wako, Saitama, Japan
            time:  Oct. 2024 - Present
            title: Postdoctoral Researcher
            content: with Dr. [Tomotaka Kuwahara](https://kuwahara-quantum.com/en/)
            description: Analytical Quantum Complexity RIKEN Hakubi Research Team, RIKEN Center for Quantum Computing

          - type: work
            place: Wako, Saitama, Japan
            time: Apr. 2023 - Sep. 2024
            title: Part-time Positions at RIKEN
            content: Junior Research Associate Program with Dr. [Tomotaka Kuwahara](https://kuwahara-quantum.com/en/)
            description: Analytical Quantum Complexity RIKEN Hakubi Research Team, RIKEN Center for Quantum Computing

          - type: study
            place: Kashiwa, Chiba, Japan
            time: Oct. 2021 - Sep. 2024
            title: Ph.D. |The University of Tokyo, Department of Physics
            content: Japanese Government (MEXT) Doctoral Scholarship with Prof. [Naomichi Hatano](http://hatano-lab.iis.u-tokyo.ac.jp/index-e.html)

          - type: study
            place: Changchun, Jilin, China
            time: Oct. 2020 - Aug. 2021
            title: MEXT Doctoral Scholarship Candidate 
            content: Preparatory School for Chinese Students to Japan

          - type: study
            place: Changchun, Jilin, China
            time: Sep. 2017 - June 2020
            title: Master of Science |Northeast Normal University, Center for Quantum Sciences
            content: Chinese National Scholarship for Postgraduates with Prof. [XueXi Yi](https://cqs.nenu.edu.cn/)
          

      - type: banner
        id: cfp
        title: Call for Papers
        icon: bullhorn
        data:
          tags: Call for Papers
          header: |-
            Special Collection: Exception Points in non-Hermitian Systems
          content: |-
            **Journal**: Discover Physics (Springer Nature)
          For inquiries, please contact: cheng.shang@riken.jp or shenhz458@nenu.edu.cn
          footer: |-
            Submission Deadline: 21 April, 2026
          actions:
            - label: Submit & Learn More
              link: https://link.springer.com/collections/djheehghia
              primary: true


          
      - type: list
        id: achievements
        title: Selected Publications
        icon: scroll
        data:
          - text: "Zhi-Guang Lu, Guo-Qing Tian, Xin-You L√º, and <span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, <i>Topological Quantum Batteries</i>, <b>Phys. Rev. Lett.</b> <b>134</b>, 180401 (2025). <br><span style=\"font-size:0.95em; color:#555;\">This work was featured in <a href=\"https://x.com/PhysRevLett/status/1924474721149542443\" target=\"_blank\">PRL Trending</a>, highlighted in a Press Release by <a href=\"https://www.riken.jp/en/news_pubs/research_news/pr/2025/20250513_2/index.html\" target=\"_blank\">RIKEN</a>, and presented as an Invited Talk at the <a href=\"https://events.physics.uoc.gr/event/1/page/5-speakers\" target=\"_blank\">21st International Workshop on Pseudo-Hermitian Hamiltonians in Quantum Physics (PHHQP-XXI)</a>, Chania, Greece. As of December 2025, this study has 62 citations on Google Scholar.</span>"
            link: "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.134.180401"

          - text: "<span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span> and Hong-Chao Li, <i>Resonance-dominant optomechanical entanglement in open quantum systems</i>, <b>Physical Review Applied</b> <b>21</b>(4), 044048 (2024). <br><span style=\"font-size:0.95em; color:#555;\">This work was an Independent Research project conducted by only two graduate students. As of December 2025, this study has 19 citations on Google Scholar.</span>"
            link: "https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.21.044048"

          - text: "<span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, Hong-Zhi Shen, and Xue-Xi Yi, <i>Nonreciprocity in a strongly coupled three-mode optomechanical circulatory system</i>, <b>Optics Express</b> <b>27</b>(18), 25882‚Äì25901 (2019). <br><span style=\"font-size:0.95em; color:#555;\">As of Dec. 2025, this work has received 34 citations on Google Scholar.</span>"
            link: "https://opg.optica.org/oe/fulltext.cfm?uri=oe-27-18-25882&id=417227"

          - text: "Hong-Zhi Shen, <span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, Y. H. Zhou, and Xue-Xi Yi, <i>Unconventional single-photon blockade in non-Markovian systems</i>, <b>Phys. Rev. A</b> <b>98</b>(2), 023856 (2018). <br><span style=\"font-size:0.95em; color:#555;\">As of December 2025, this work has received 89 citations on Google Scholar.</span>"
            link: "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.98.023856"

          - text: "Zhi-Guang Lu, <span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, Ying Wu, and Xin-You L√º, <i>Analytical approach to higher-order correlation functions in U(1) symmetric systems</i>, <b>Phys. Rev. A</b> <b>108</b>, 053703 (2023). <br><span style=\"font-size:0.95em; color:#555;\">This work developed a user-friendly open-source library in Python known as the <a href=\"https://github.com/ZhiGuangLu/qcs\" target=\"_blank\" rel=\"noopener noreferrer\">Quantum Correlation Solver</a>.</span>"
            link: "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.108.053703"


      - type: list
        id: preprints
        title: Selected Preprints
        icon: clock-rotate-left
        data:
          - text: "<span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, Zhi-Guang Lu, Hayato Kinkawa, and Tomotaka Kuwahara, <i>Operator Spreading and Information Propagation: Equivalence and Beyond</i>, <b>arXiv</b>:2505.07955. <br><span style=\"font-size:0.95em; color:#555;\">This work received the <a href=\"http://en.baqis.ac.cn/news/detail/?cid=1764\" target=\"_blank\" rel=\"noopener noreferrer\">Best Poster Award</a> at the 5th International Symposium on Quantum Physics and Quantum Information Sciences (QPQIS-2023), Beijing, China.</span>"
            link: "https://arxiv.org/abs/2505.07955"

          - text: "Donghoon Kim, Yusuke Kimura, Hugo Mackay, Yosuke Mitsuhashi, Hideaki Nishikawa, Carla Rubiliani, <span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, Ayumi Ukai, and Tomotaka Kuwahara, <i>Spectral Small-Incremental-Entangling: Breaking Quasi-Polynomial Complexity Barriers in Long-Range Interacting Systems</i>, <b>arXiv</b>:2509.12014. <br><span style=\"font-size:0.95em; color:#555;\">This work, an International Collaboration across Asia, Europe, and the U. S., introduces the concept of spectral entangling strength (SIE), which captures the structural entangling power of an operator, and establishes a spectral SIE theorem.</span>"
            link: "https://arxiv.org/abs/2509.12014"

          - text: "Hongchao Li, <span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, Tomotaka Kuwahara, and Tan Van Vu, <i>Macroscopic Particle Transport in Dissipative Long-Range Bosonic Systems</i>, <b>arXiv</b>:2503.13731. <br><span style=\"font-size:0.95em; color:#555;\">This work is currently under review at <i>Nature Communications</i>.</span>"
            link: "https://arxiv.org/abs/2503.13731"

          - text: "H. Z. Shen, X. C. Zhang, L. Y. Ning, Zhi-Guang Lu, and <span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span>, <i>Higher-order Exceptional Points Induced by Non-Markovian Environments</i>, <b>arXiv</b>:2504.00617. <br><span style=\"font-size:0.95em; color:#555;\">This work will be submitted to <i>PRX Quantum</i> soon.</span>"
            link: "https://arxiv.org/abs/2504.00617"

          - text: "<span style=\"color:#6b5b95; font-weight:800;\">Cheng Shang</span> and H. Z. Shen, <i>Coupling Enhancement and Symmetrization in Dissipative Optomechanical Systems</i>, <b>arXiv</b>:2302.04897. <br><span style=\"font-size:0.95em; color:#555;\">This work is an invited contribution to <i>Annalen der Physik</i> and is currently under review.</span>"
            link: "https://arxiv.org/abs/2302.04897"

      - type: list
        id: interests
        title: Research Interests
        icon: flask
        dot: check
        data:
          - "**‚ñº Lieb-Robinson Bound and Its Application**: one may include Particle Transport, Information Propagation, Operator Spreading, and Correlation Generation."
          - "**‚ñ£ Open Quantum Systems**: with particular focus on Dissipative and non-Markovian Dynamics in Quantum Optics and Quantum Information."
          - "**‚óé Quantum Batteries**: focuses on improving the performance of Quantum Batteries by addressing theoretical barriers in practical applications, including those in Topological and Many-Body Quantum Systems."
          - "**|‚óªÔ∏é| Hybrid Cavity Optomechanics**: theoretical exploration of nonlinear radiation-pressure-induced phenomena and their integration with Superconducting Circuit platforms." 

      - type: list
        id: future
        title: What I Want to Learn
        icon: fa6-solid:book
        dot: pencil
        data:
          - text: "**Many-body localization and thermalization** (from an information-theoretic perspective)"
          - text: "**Floquet theory** (periodic driving theory and Floquet heating)"
          - text: "**Quantum Complexity and Krylov complexity**"
          - text: "**Advanced mathematics** (von Neumann algebras and graph theory)"


    footer:
          copyright: "¬© 2025 Cheng Shang. All rights reserved. <br>‚ü≥ Update: December 26, 2025"
